
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: localhost:5000/backend:latest
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:mysecretpassword@postgresql:5432/tododb"
