apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: my-todo
spec:
  type: LoadBalancer 
  ports:
    - port: 8001          
      targetPort: 8001    
      protocol: TCP
  selector:
    app: nginx
