version: '3'

services:
  backend:
    image: localhost:5000/backend
  #  ports:
  #    - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgresql/tododb
    networks:
      - todo-network
  frontend:
    image: localhost:5000/frontend
 #   ports:
 #     - "3000:3000"
    networks:
      - todo-network
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tododb
#    ports:
 #     - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql  
    networks:
      - todo-network
  nginx:
    image: nginx:latest
    ports:
      - "8001:8001"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
    networks:
      - todo-network
volumes:
  postgres_data:


networks:
  
  todo-network:
    driver: overlay